title: "My GitHub Pages"
author: "Dan Zhang"
description: "<b>The world's a playground. You know that when you are a kid, but somewhere along the way everyone forgets it.</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dan.zhang.1@stonybrook.edu"}
  - {title: Github, icon: github, url: "https://github.com/SUNY-Dan"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-remote-theme

remote_theme: niklasbuschmann/contrast@v2.6


